name: 4-bit CPU tests
on:
  push:
    paths:
      - four-bit-computer/**

jobs:
  test-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} has been cloned to the runner"

      - name: Test Scanner
        run: |
          cd four-bit-computer/assembler
          python -m test.test_scanner

  test-parser:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout repository code
            uses: actions/checkout@v4
          - run: echo "The ${{ github.repository }} has been cloned to the runner"

          - name: Test Parser
            run: |
              cd four-bit-computer/assembler
              python -m test.test_parser

  test-code-generator:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository code
          uses: actions/checkout@v4
        - run: echo "The ${{ github.repository }} has been cloned to the runner"

        - name: Test Code Generator
          run: |
            cd four-bit-computer/assembler
            python -m test.test_code_generator