name: 4-bit CPU tests
on: [push]

jobs:
  test-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} has been cloned to the runner"

      - name: Test scanner
        run: |
          cd four-bit-computer/assembler
          python -m test.test_scanner